debug: true
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://xxx:3306/his?serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20

      max-wait: 30000

      time-between-eviction-runs-millis: 60000

      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20



server:
  servlet:
    context-path: /his
  port: 8099



#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.his.app.pojo


swagger:
  enable: true
logging:
  level: error
  file:
    path: /log